### ISSUE TITLE
Trim last slash from HA_URL

### ISSUE THREAD

**Issue by clau-bucur** [sagilo/home-assistant-watchdog#2]
If the configured HA_URL ends with a slash the script will fail with 404.
It took a while to figure out that the culprit was that I configured the HA_URL including the last /.

Maybe it'd helpful to trim it down before accessing '/api'.

**Comment by sagilo** [comment]
[Added a verification](https://github.com/sagilo/home-assistant-watchdog/commit/2e3fe5747dc5e14f713b95abbdcc94b2db1e8f45) so a clear exception will be thrown if `HA_URL` is invalid
